market/conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

market/core/urls.py
from django.contrib.auth import views as auth_views #we change the name because otherwise it clash with views 
from django.urls import path 

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path("", views.index, name="index"),
    path("feedback/", views.review, name="review"),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html', authentication_form=LoginForm), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='base.html'), name='logout'),
]

market/item/urls.py
from django.urls import path
from .views import *

app_name = 'item'

urlpatterns = [
    path('', items, name="items"),
    path('new/', new, name="new"),
    path('<int:pk>/', detail, name="detail"),
    path('<int:pk>/edit', edit, name="edit"),
    path('<int:pk>/delete', delete, name="delete"),
]

market/market/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('core.urls')),
    path("items/",include('item.urls')),
    path("dashboard/", include("dashboard.urls")),
    path("conversation/", include("conversation.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/item/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE) #It's a foreign key field, which means it will establish a link between Item and Category models. An item will be associated with a category."related_name='items'":It means that we can access all items associated with a category using category.items.all(). 'on_delete=models.CASCADE': which means that when a Category is deleted, all associated Item records will also be deleted.
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True) #Django will created the uploaded folder for us if it doesn't exist. In case the user doesn't want to provide an image so black = True and null = True 
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    
    

market/item/forms.py
from django import forms
from .models import Item

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)
        widgets = {
            'category': forms.Select(attrs={
                'class': 'form-control'
            }),
            'name': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control'
            }),
            'price': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'image': forms.FileInput(attrs={
                'class': 'form-control'
            })
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image','is_sold')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control'
            }),
            'price': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'image': forms.FileInput(attrs={
                'class': 'form-control'
            })
        }

market/item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q #This is use for search multiple fields 
from django.shortcuts import render, get_object_or_404, redirect
from .forms import NewItemForm, EditItemForm
from .models import *

# Create your views here.
def items(request):
    query = request.GET.get('query', '')#'' means else empty
    items = Item.objects.filter(is_sold=False)
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
       items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))


    return render(request, 'items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk) #Django will give us a 404 error if this object doesn't exist in the database. Left pk(primary key) is the primary key of the model itself and right pk is the one we get from the url
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'detail.html', {
        'item': item,
        'related_items': related_items
    })

@login_required #so without authenticate person will be redirected to the loginpage
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)#create object but not save in the database
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'form.html', {
        'form': form,
        'title': 'Create new item',
    })


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
   
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        
        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=item.id)

    else:
        form = EditItemForm(instance=item)

    return render(request, 'form.html', {
        'form': form,
        'title': 'Edit item',
    })

market/item/templates/detail.html
{% extends 'base.html' %}

{% block title %} {{ item.name }} {% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <!-- Left Column (Image) -->
        <div class="col-md-6">
            <img src="{{ item.image.url }}" alt="Image" class="img-fluid">
        </div>

        <!-- Right Column (Image Details) -->
        <div class="col-md-6">
            <h2>{{ item.name }}</h2>
            <p><strong>Price: </strong>{{ item.price }}</p>
            <p><strong>Seller: </strong>{{ item.created_by.username }}</p>
            {% if item.description %}
            <p><strong>Description: </strong>{{ item.description }}</p>
            <!-- Add more image details here -->
            {% endif %}
            <div class="mt-4">
                {% if request.user == item.created_by %}
                <a style="border: 1px solid #C0C0C0;" href="{% url 'item:edit' item.id %}" class="btn btn-light"><sub><ion-icon name="create-outline" style="font-size: 20px;"></ion-icon></sub> Edit</a>
                <a style="border: 1px solid #C0C0C0;" href="{% url 'item:delete' item.id %}" class="btn btn-light"><sub><ion-icon name="close-circle-outline" style="font-size: 20px;"></ion-icon></sub> Delete</a>
                {% else %}
                <a style="border: 1px solid #C0C0C0;" href="{% url 'conversation:new' item.id %}" class="btn btn-light"><sub><ion-icon name="paper-plane-outline" style="font-size: 20px;"></ion-icon></sub> Contact Seller</a>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Related items section -->
    <h2 class="mt-5 text-center">Related Items</h2>
    <div class="row">
        {% for related_item in related_items %}
        <!-- Card -->
        <div class="col-md-4">
            <a href="{% url 'item:detail' related_item.id %}" class="text-decoration-none">
                <div class="card mb-4">
                    <img src="{{ related_item.image.url }}" class="card-img-top" alt="{{ related_item.name }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ related_item.name }}</h5>
                        <p class="card-text">Price: {{ related_item.price }}</p>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

market/item/templates/form.html
{% extends 'base.html' %}
{% block title %} {{title}} {% endblock %}
{% block content %}
  <div class="row justify-content-center align-items-center">
    <div class="col-md-6 my-3">
      <div style="text-align: center;" class="icon">
        <ion-icon name="create-sharp" style="font-size: 50px;"></ion-icon>
      </div>
<h1 style="text-align: center;">{{title}}</h1>
<div style="margin-bottom: 10px;">
<form method="post" enctype="multipart/form-data"><!--enctype is required for image-->
    {% csrf_token %}
    <div class="mb-3">
        {{ form.as_p }}
      </div>
      {% if form.errors or form.non_field_errors %}
      <div class="mb-3 p-6 bg-red-100 rounded-xl">
          {% for field in form %}
              {{ field.errors }}
          {% endfor %}
          {{ form.non_field_errors }}
      </div>
  {% endif %}
    <button style="border: 1px solid #C0C0C0;"  type="submit" class="btn btn-light">Submit <sub><ion-icon name="send-outline" style="font-size: 18px;"></ion-icon></sub></button>
  </form>
</div>
</div>
</div>
{% endblock %}

market/item/templates/items.html
{% extends 'base.html' %}
{% block title %}Items{% endblock %}
{% block content %}
    <div class="row">
        <!-- Fixed Sidebar -->
        <div class="col-md-3 my-5 fixed-sidebar">
            <!-- Sidebar Content -->
            <form method="get" action="{% url 'item:items' %}">
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="query" placeholder="Search an item" aria-label="Search an item" aria-describedby="search-button">
                    <button style="border: 1px solid #C0C0C0;"  class="btn btn-light" type="submit" id="search-button"><sub><ion-icon name="search-outline" style="font-size: 18px;"></ion-icon></sub> Search</button>
                </div>
            </form>
            <hr class="my-4">
            <!-- <h3>Categories</h3> -->
            <div class="list-group">
                <a href="{% url 'item:items' %}" class="list-group-item list-group-item-action" aria-current="true">
                   All categories
                </a>
                {% for category in categories %}
                <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}" class="list-group-item list-group-item-action">{{ category.name }}</a>
                {% endfor %}
              </div>
        </div>
        <!-- Content Area -->
        <div class="col-md-9 content">
            <h2 class="my-3"><sub><ion-icon name="pricetags-outline" style="font-size: 30px;"></ion-icon></sub> All Items</h2>
            <div class="row">
                {% for item in items %}
                <!-- Card -->
                <div class="col-md-4">
                    <a href="{% url 'item:detail' item.id %}" class="text-decoration-none">
                        <div class="card mb-4">
                            <img src="{{item.image.url}}" class="card-img-top" alt="{{ item.name }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ item.name }}</h5>
                                <p class="card-text">Price: {{ item.price }}</p>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}