market/conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

market/core/urls.py
from django.contrib.auth import views as auth_views #we change the name because otherwise it clash with views 
from django.urls import path 

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path("", views.index, name="index"),
    path("feedback/", views.review, name="review"),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html', authentication_form=LoginForm), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='base.html'), name='logout'),
]

market/dashboard/urls.py
from django.urls import path 
from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.index, name="index")
]

market/item/urls.py
from django.urls import path
from .views import *

app_name = 'item'

urlpatterns = [
    path('', items, name="items"),
    path('new/', new, name="new"),
    path('<int:pk>/', detail, name="detail"),
    path('<int:pk>/edit', edit, name="edit"),
    path('<int:pk>/delete', delete, name="delete"),
]

market/market/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('core.urls')),
    path("items/",include('item.urls')),
    path("dashboard/", include("dashboard.urls")),
    path("conversation/", include("conversation.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/core/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()
    is_viewed = models.BooleanField(default=False)

    def __str__(self):
        return self.name


        

market/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Review

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'form-control'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'form-control'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User #This model is comes from django
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'form-control'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'form-control'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'form-control'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'form-control'
    }))

class FeedbackForm(ModelForm):
    class Meta:
        model = Review
        fields = '__all__'

market/core/views.py
from django.shortcuts import render,redirect
from item.models import Category, Item
from core.models import Review
from .forms import SignupForm, FeedbackForm
# Create your views here.

def index(request):
    items = Item.objects.filter(is_sold=False)[0:8] #because we don't want product that is sold
    categories = Category.objects.all()
    reviews = Review.objects.filter(is_viewed=True)

    return render(request, 'index.html', {
        'categories': categories,
        'items': items,
        'reviews': reviews,
    })

def review(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:index')
    form = FeedbackForm()
    context = {'form': form}
    return render(request, 'review.html',context)

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()
        
    return render(request, 'signup.html', {
        'form': form
    })

market/core/templates/base.html
<!doctype html>
 <html lang="en">
   <head>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">

     <title>{% block title %} {% endblock %} | Market</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
   </head>
   <body>
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
          <!-- Logo or Brand Name -->
          <a class="navbar-brand" href="{% url 'core:index' %}">Crack The Shop</a>
  
          <!-- Toggle Button for Mobile -->
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
  
          <!-- Navigation Links -->
          <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'item:new' %}">New Item</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'core:review' %}">Feedback</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'item:items' %}">Browse</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'dashboard:index' %}">Dashboard</a>
                  </li>
              </ul>
          </div>
  
          <!-- User Actions (Login, Logout, Inbox) -->
          <div class="nav-item">
              {% if request.user.is_authenticated %}
                  <a class="nav-link" href="{% url 'core:logout' %}"><sub><ion-icon name="backspace-outline" style="font-size: 20px;"></ion-icon></sub> Logout</a>
                  <a class="nav-link" href="{% url 'conversation:inbox' %}"><sub><ion-icon name="chatbubbles-outline"  style="font-size: 20px;"></ion-icon></sub> Inbox</a>
              {% else %}
              <a class="btn btn-light" href="{% url 'core:signup' %}">
                <sub><ion-icon name="person-add-outline" style="font-size: 15px;"></ion-icon></sub> Signup
            </a>
                  <a class="btn btn-light" href="{% url 'core:login' %}"><sub><ion-icon name="log-in-outline" style="font-size: 18px;"></ion-icon></sub> Login</a>
              {% endif %}
          </div>
      </div>
  </nav>
    <!--End Navbar-->
    
    <!--Main contain-->
   <div class="container">

    {% block content %}
    {% endblock %}

    </div>
    <!--End Main contain-->

    <!--footer-->
    <footer class="bg-body-tertiary text-center text-body-secondary py-4">
      <div class="container">
          <p>This template built for <a style="text-decoration: none;" href="#">ShoppingSite</a> by <a style="text-decoration: none;" href="#">@iftakhirnibir</a>.</p>
          <p class="mb-0">
              <a style="text-decoration: none;" href="#top">Back to top</a>
          </p>
      </div>
    </footer> 
    <!--End footer--> 
     <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
     <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
   </body>
 </html>

market/core/templates/index.html
{% extends 'base.html' %}

{% block title %} Welcome {% endblock %}

{% block content %}
<div class="container">
  <div class="row">
      <div class="col-md-6">
          <img src="https://img.freepik.com/premium-vector/girl-doing-online-shopping-by-smartphone_701961-2321.jpg" alt="" class="img-fluid">
      </div>
      <div style="padding: 80px;" class="col-md-6">
          <h1 class="mt-4 mt-md-0">Online Shopping Site</h1>
          <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae nam officia dolores amet aliquam, magnam consequuntur vitae labore fugit dolorum placeat illo praesentium corrupti ab. Corrupti dicta similique dolorem rerum?
          </p>
      </div>
  </div>
</div>




<div style="display: flex;">
<hr style="flex-grow: 1;">
<h2 style="text-align: center; margin: 0 10px; margin-bottom: 8px;" >Categories</h2>
<hr style="flex-grow: 1;">
</div>
<div style="margin-bottom: 8px;" class="categories">
    <!-- Start of the Bootstrap row -->
    <div class="row">
      {% for category in categories %}
      <!-- Card -->
      <div class="col-md-4">
          <div class="card">
              <div class="card-body">
                  <h5 class="card-title">{{category.name}}</h5>
                  <p class="card-text">{{category.items.count}} items</p>
              </div>
          </div>
      </div>
      {% endfor %}
  </div> <!-- End of the category row -->
  </div>

<div style="display: flex;">
    <hr style="flex-grow: 1;">
    <h2 style="text-align: center; margin: 0 10px; margin-bottom: 8px;" >Newest items</h2>
    <hr style="flex-grow: 1;">
</div>
<div class="item">
  <!-- Start of the Bootstrap row -->
  <div class="row">
    {% for item in items %}
    <!-- Card -->
    <div class="col-md-3">
        <a style="text-decoration: none;" href="{% url 'item:detail' item.id %}"> <!--Here item: is the app_name-->
        <div class="card" style="margin-bottom: 15px;">
            <img src="{{item.image.url}}" class="card-img-top" alt="Image 1" width="200px" height="200px">
            <div class="card-body">
                <h5 class="card-title">{{item.name}}</h5>
                <p class="card-text">$ {{item.price}}</p>
            </div>
        </div>
    </a>
    </div>
    {% endfor %}
</div> <!-- End of the item row -->
</div>

  <div class="reviews">
    <div style="display: flex; margin-bottom: 8px;">
        <hr style="flex-grow: 1">
        <h2 style="text-align: center; margin: 0 10px;">Customer Review</h2>
        <hr style="flex-grow: 1">
    </div>
    
    <div class="row" style="margin-bottom: 15px;">
      {% for review in reviews %}
        <div class="col-sm-6 mb-3 mb-sm-0">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><sub><ion-icon name="person-circle-outline" style="font-size: 22px;"></ion-icon></sub> {{review.name}}</h5>
              <p>{{review.email}}</p>
              <hr>
              <p class="card-text">{{review.message}}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
  </div>
{% endblock %}

market/core/templates/login.html
{% extends 'base.html' %}
{% block title %} SignUp {% endblock %}
{% block content %}
<div style="margin-bottom: 85px;" class="row justify-content-center align-items-center">
  <div class="col-md-6 my-4">
    <div style="text-align: center;" class="icon">
      <ion-icon name="log-in-sharp" style="font-size: 50px;"></ion-icon>
    </div>
<h1 style="text-align: center;">Log In</h1>
<form method="post" action="."><!--action dot means return action on the same page-->
    {% csrf_token %}
    <div class="mb-3">
        <label for="username" class="form-label">Username</label><br>
        {{form.username}}
      </div>
      <div class="mb-3">
        <label for="password1" class="form-label">Password</label><br>
        {{form.password}}
      </div>
      {% if form.errors or form.non_field_errors %}
      <div class="mb-3 p-6 bg-red-100 rounded-xl">
          {% for field in form %}
              {{ field.errors }}
          {% endfor %}

          {{ form.non_field_errors }}
      </div>
  {% endif %} 
    <button style="border: 1px solid #C0C0C0;" type="submit" class="btn btn-light">Submit <sub><ion-icon name="send-outline" style="font-size: 18px;"></ion-icon></sub></button>
  </form>
</div>
</div>
{% endblock %}

market/core/templates/review.html
{% extends 'base.html' %}
{% block title %}Feedback{% endblock %}
{% block content %} 
    <div class="row justify-content-center align-items-center" style="height: 80vh;">
        <div class="col-md-6">
            <div style="text-align: center;" class="icon">
                <ion-icon name="mail-unread-outline" style="font-size: 50px;"></ion-icon>
              </div>
            <h1 class="text-center">Give Your Feedback Here</h1>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label class="form-label">Username</label>
                    {% if request.user.is_authenticated %}
                    <input type="text" class="form-control" name="name" value="{{request.user.username}}">
                    {% else %}
                    <input type="text" class="form-control" name="name">
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label class="form-label">Email address</label>
                    {% if request.user.is_authenticated %}
                    <input type="email" class="form-control" name="email" value="{{request.user.email}}">
                    {% else %}
                    <input type="email" class="form-control" name="email">
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label class="form-label">Message</label>
                    <textarea class="form-control" name="message" rows="3"></textarea>
                </div>
                <button style="border: 1px solid #C0C0C0;" type="submit" class="btn btn-light">Submit <sub><ion-icon name="send-outline" style="font-size: 18px;"></ion-icon></sub></button>
            </form>
        </div>
    </div>
{% endblock %}

market/core/templates/signup.html
{% extends 'base.html' %}
{% block title %} SignUp {% endblock %}
{% block content %}
<div class="row justify-content-center align-items-center">
  <div class="col-md-6 my-3">
    <div style="text-align: center;" class="icon">
  <ion-icon name="person-add-sharp" style="font-size: 50px;"></ion-icon>
</div>
<h1 style="text-align: center;">Sign Up</h1>
<form method="post" action="."><!--action dot means return action on the same page-->
    {% csrf_token %}
    <div class="mb-3">
        <label for="username" class="form-label">Username</label><br>
        {{form.username}}
      </div>
      <div class="mb-3">
        <label for="email" class="form-label">Email</label><br>
        {{form.email}}
      </div>
      <div class="mb-3">
        <label for="password1" class="form-label">Password</label><br>
        {{form.password1}}
      </div>
      <div class="mb-3">
        <label for="password2" class="form-label">Repeat Password</label><br>
        {{form.password2}}
      </div>

      {% if form.errors or form.non_field_errors %}
      <div class="mb-3 p-6 bg-red-100 rounded-xl">
          {% for field in form %}
              {{ field.errors }}
          {% endfor %}

          {{ form.non_field_errors }}
      </div>
  {% endif %}
  
    <button style="border: 1px solid #C0C0C0;" type="submit" class="btn btn-light">Submit <sub><ion-icon name="send-outline" style="font-size: 18px;"></ion-icon></sub></button>
  </form>
</div>
</div>
{% endblock %}